# Generated by Django 4.2.20 on 2025-03-29 23:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name_en', models.CharField(max_length=100, verbose_name='type name (English)')),
                ('type_name_ar', models.CharField(max_length=100, verbose_name='type name (Arabic)')),
                ('description_en', models.TextField(verbose_name='description (English)')),
                ('description_ar', models.TextField(verbose_name='description (Arabic)')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=255, verbose_name='name (English)')),
                ('description_en', models.TextField(verbose_name='description (English)')),
                ('name_ar', models.CharField(blank=True, max_length=255, verbose_name='name (Arabic)')),
                ('description_ar', models.TextField(blank=True, verbose_name='description (Arabic)')),
                ('event_by', models.CharField(max_length=255, verbose_name='organized by')),
                ('event_date', models.DateTimeField(verbose_name='start date')),
                ('end_date', models.DateTimeField(verbose_name='end date')),
                ('location', models.CharField(max_length=255, verbose_name='location')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.eventtype')),
            ],
        ),
        migrations.CreateModel(
            name='Rsvp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('going', 'Going'), ('interested', 'Interested'), ('not_going', 'Not Going')], default='interested', max_length=10, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'RSVP',
                'verbose_name_plural': 'RSVPs',
                'unique_together': {('user', 'event')},
            },
        ),
    ]
